
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Alchemy','the study of transmutation of substances into other forms.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Herbology','the study of magical plants and how to take care of, utilise and combat them.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('History of Magic','the study of magical history.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Potions','the art of creating mixtures with magical effects.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Muggle Studies','the study of the Muggle culture "from a wizarding point of view".', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Dark Arts','the study of defensive techniques to defend against the Dark Arts.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Charms','the study of spells concerned with giving an object new properties.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Flying','the study of flying of broomsticks.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Magical Theory','the study of  magic from a purely theoretical view.', 'true');
INSERT INTO timetable.lessons (lesson_name, description, isActive) VALUES ('Ghoul Studies','the study of ghouls  and  other similar creatures.', 'true');


INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('CO-68', 1, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('FW-72', 1, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('OQ-07', 1, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('SG-63', 1, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('GW-21', 1, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('OB-14', 2, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('HN-86', 2, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('RI-38', 2, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('FD-15', 2, true);
INSERT INTO timetable.groups (group_name, department_id, isActive) VALUES ('CX-49', 2, true);

insert into timetable.rooms (room_id, capacity) values (101, 21);
insert into timetable.rooms (room_id, capacity) values (102, 26);
insert into timetable.rooms (room_id, capacity) values (201, 30);
insert into timetable.rooms (room_id, capacity) values (202, 15);
insert into timetable.rooms (room_id, capacity) values (203, 25);
insert into timetable.rooms (room_id, capacity) values (204, 30);
insert into timetable.rooms (room_id, capacity) values (301, 29);
insert into timetable.rooms (room_id, capacity) values (302, 26);
insert into timetable.rooms (room_id, capacity) values (303, 25);
insert into timetable.rooms (room_id, capacity) values (401, 19);


INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Potter', 1, 1234, '1IE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Finch-Fletchley', 1, 1234, '2WC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Brocklehurst', 1, 1234, '3SN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Granger', 1, 1234, '4LV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Parkinson', 1, 1234, '5QL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Thomas', 1, 1234, '6JH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Bones', 1, 1234, '7YC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finnigan', 1, 1234, '8KU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Weasley', 1, 1234, '9PH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Thomas', 1, 1234, '10WP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Potter', 1, 1234, '11ZG', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Corner', 1, 1234, '12PB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Boot', 1, 1234, '13PC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Finch-Fletchley', 1, 1234, '14OL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Turpin', 1, 1234, '15IU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Patil', 1, 1234, '16ID', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Longbottom', 1, 1234, '17DA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Finch-Fletchley', 1, 1234, '18SA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Abbott', 1, 1234, '19LN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Thomas', 1, 1234, '20JW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Longbottom', 1, 1234, '21JP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Potter', 1, 1234, '22HK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Turpin', 1, 1234, '23KY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Thomas', 1, 1234, '24HU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Brown', 1, 1234, '25BJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Longbottom', 1, 1234, '26AN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Potter', 1, 1234, '27HB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Potter', 1, 1234, '28JK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Granger', 1, 1234, '29VV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Brocklehurst', 2, 1234, '2NJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Brocklehurst', 2, 1234, '4CC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Nott', 2, 1234, '6PO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Patil', 2, 1234, '8SL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Weasley', 2, 1234, '10JW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Macmillan', 2, 1234, '12HX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Patil', 2, 1234, '14EB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Finnigan', 2, 1234, '16QD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finnigan', 2, 1234, '18IR', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Abbott', 2, 1234, '20PD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Corner', 2, 1234, '22YK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Goldstein', 2, 1234, '24NP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Boot', 2, 1234, '26BO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Patil', 2, 1234, '28BF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Goldstein', 2, 1234, '30WC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Finch-Fletchley', 2, 1234, '32EY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Patil', 2, 1234, '34SU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Weasley', 3, 1234, '3LN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Nott', 3, 1234, '6HO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Patil', 3, 1234, '9AT', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Brown', 3, 1234, '12LA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Boot', 3, 1234, '15VK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Macmillan', 3, 1234, '18AV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Turpin', 3, 1234, '21AY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Turpin', 3, 1234, '24IH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Boot', 3, 1234, '27ZX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Goldstein', 3, 1234, '30LD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Patil', 3, 1234, '33BR', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Finnigan', 4, 1234, '4BP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Finnigan', 4, 1234, '8SC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Goldstein', 4, 1234, '12GS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Weasley', 4, 1234, '16BM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Brown', 4, 1234, '20QM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Finch-Fletchley', 4, 1234, '24NF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Nott', 4, 1234, '28QE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Longbottom', 4, 1234, '32DP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Abbott', 4, 1234, '36YI', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Brocklehurst', 4, 1234, '40KW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Thomas', 4, 1234, '44EP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Parkinson', 4, 1234, '48AF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Patil', 4, 1234, '52JB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Patil', 4, 1234, '56WL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Boot', 4, 1234, '60FY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Boot', 4, 1234, '64SG', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Finnigan', 4, 1234, '68VS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Nott', 4, 1234, '72ND', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Potter', 4, 1234, '76TD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Granger', 4, 1234, '80QM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Parkinson', 4, 1234, '84BB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Patil', 4, 1234, '88ED', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Brown', 4, 1234, '92PI', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Potter', 4, 1234, '96CJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Goldstein', 4, 1234, '100PJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Brocklehurst', 4, 1234, '104UU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Corner', 5, 1234, '5NL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Nott', 5, 1234, '10CS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Neville', 'Goldstein', 5, 1234, '15CE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Potter', 5, 1234, '20FV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Macmillan', 5, 1234, '25BB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Patil', 5, 1234, '30EE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Potter', 5, 1234, '35YS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Nott', 5, 1234, '40TS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Granger', 5, 1234, '45YF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Abbott', 5, 1234, '50XJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Potter', 5, 1234, '55EP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Neville', 'Brocklehurst', 5, 1234, '60IM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Longbottom', 5, 1234, '65DU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Potter', 5, 1234, '70FL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Longbottom', 5, 1234, '75SS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Patil', 5, 1234, '80LA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Boot', 5, 1234, '85ZP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Bones', 5, 1234, '90RM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Parkinson', 5, 1234, '95TK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Boot', 5, 1234, '100KW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Patil', 5, 1234, '105PF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Parkinson', 5, 1234, '110WB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Macmillan', 5, 1234, '115MJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Boot', 5, 1234, '120KO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Finnigan', 5, 1234, '125RF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Boot', 6, 1234, '6FT', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Goldstein', 6, 1234, '12DI', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Corner', 6, 1234, '18CF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Thomas', 6, 1234, '24RI', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Thomas', 6, 1234, '30HO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Brocklehurst', 6, 1234, '36RC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Finnigan', 6, 1234, '42WU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Bones', 6, 1234, '48NN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Goldstein', 6, 1234, '54MW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Finnigan', 6, 1234, '60EU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Patil', 6, 1234, '66VK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Turpin', 6, 1234, '72OU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Brown', 7, 1234, '7PQ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Neville', 'Patil', 7, 1234, '14QB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Abbott', 7, 1234, '21DJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Patil', 7, 1234, '28BE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Potter', 7, 1234, '35ZS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Weasley', 7, 1234, '42UY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Finnigan', 7, 1234, '49RL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Granger', 7, 1234, '56YA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Finnigan', 7, 1234, '63UE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Finch-Fletchley', 7, 1234, '70XP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Turpin', 7, 1234, '77SD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Patil', 7, 1234, '84AJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Finnigan', 7, 1234, '91HL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Macmillan', 7, 1234, '98VH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Nott', 7, 1234, '105XE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Parkinson', 7, 1234, '112MF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Thomas', 7, 1234, '119PX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Abbott', 7, 1234, '126MP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Patil', 7, 1234, '133WK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Macmillan', 7, 1234, '140DX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Macmillan', 7, 1234, '147BF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Parkinson', 7, 1234, '154KU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Brocklehurst', 7, 1234, '161UH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Longbottom', 7, 1234, '168DZ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Granger', 7, 1234, '175QU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Brocklehurst', 7, 1234, '182UO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Finnigan', 7, 1234, '189XU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Finnigan', 7, 1234, '196XW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Patil', 8, 1234, '8VI', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Macmillan', 8, 1234, '16EU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Potter', 8, 1234, '24EG', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Longbottom', 8, 1234, '32GD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Thomas', 8, 1234, '40VC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Weasley', 8, 1234, '48WM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Parkinson', 8, 1234, '56XM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Bones', 8, 1234, '64JX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Patil', 8, 1234, '72PY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Goldstein', 8, 1234, '80MT', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hannah', 'Brown', 8, 1234, '88VC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Neville', 'Goldstein', 8, 1234, '96KX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Brocklehurst', 8, 1234, '104BB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finnigan', 8, 1234, '112AP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Goldstein', 8, 1234, '120JO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Parkinson', 8, 1234, '128HU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Finnigan', 8, 1234, '136CL', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Thomas', 8, 1234, '144ME', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Finnigan', 8, 1234, '152CP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Parkinson', 8, 1234, '160WJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Patil', 8, 1234, '168QJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Parkinson', 8, 1234, '176YP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Susan', 'Turpin', 8, 1234, '184SV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Goldstein', 8, 1234, '192BW', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Potter', 8, 1234, '200IX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Turpin', 8, 1234, '208QA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Longbottom', 8, 1234, '216JD', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Finch-Fletchley', 8, 1234, '224SB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Pansy', 'Nott', 8, 1234, '232WE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Abbott', 9, 1234, '9OB', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Bones', 9, 1234, '18ZV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Padma', 'Corner', 9, 1234, '27ZR', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Goldstein', 9, 1234, '36KP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Potter', 9, 1234, '45LH', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Terry', 'Corner', 9, 1234, '54PU', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Boot', 9, 1234, '63PZ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Boot', 9, 1234, '72HN', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Potter', 9, 1234, '81YC', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Justin', 'Turpin', 9, 1234, '90PY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Longbottom', 9, 1234, '99PZ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Parkinson', 10, 1234, '10DK', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Corner', 10, 1234, '20RF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Finch-Fletchley', 10, 1234, '30RX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finch-Fletchley', 10, 1234, '40RJ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Harry', 'Finch-Fletchley', 10, 1234, '50ES', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Weasley', 10, 1234, '60EV', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Abbott', 10, 1234, '70XX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Abbott', 10, 1234, '80GF', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Abbott', 10, 1234, '90JO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lisa', 'Bones', 10, 1234, '100OM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Parvati', 'Longbottom', 10, 1234, '110TE', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finnigan', 10, 1234, '120FO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Seamus', 'Parkinson', 10, 1234, '130YS', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Thomas', 10, 1234, '140ZO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Weasley', 10, 1234, '150TT', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Theodore', 'Abbott', 10, 1234, '160OA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Anthony', 'Goldstein', 10, 1234, '170OP', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Michael', 'Granger', 10, 1234, '180QO', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Hermione', 'Potter', 10, 1234, '190AA', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Lavender', 'Corner', 10, 1234, '200NQ', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Dean', 'Corner', 10, 1234, '210YM', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ronald', 'Corner', 10, 1234, '220JY', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Longbottom', 10, 1234, '230UX', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Mandy', 'Nott', 10, 1234, '240CR', 'true');
INSERT INTO timetable.students (first_name, last_name, group_id, password, id_card, isActive) VALUES ('Ernie', 'Finnigan', 10, 1234, '250KM', 'true');


INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Albus', 'Dumbledore', 'professor', 555, 1, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Minerva', 'McGonagall', 'lecturer', 555, 1, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Severus', 'Snape', 'professor', 555, 1, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Filius', 'Flitwick', 'professor', 555, 1, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Remus', 'Lupin', 'assistant', 555, 1, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Barty', 'Crouch', 'professor', 555, 2, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Horace', 'Slughorn', 'lecturer', 555, 2, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Dolores', 'Umbridge', 'assistant', 555, 2, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Rubeus', 'Hagrid', 'lecturer', 555, 2, 'true');
INSERT INTO timetable.teachers (first_name, last_name, position, password, department_id, isActive) VALUES ('Pomona', 'Sprout', 'professor', 555, 2, 'true');

insert into timetable.lessons_teachers (lesson_id, teacher_id) values (1, 1);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (1, 2);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (2, 3);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (2, 4);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (3, 5);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (3, 6);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (4, 7);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (4, 8);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (5, 9);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (5, 10);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (6, 1);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (6, 2);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (7, 3);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (7, 4);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (8, 5);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (8, 6);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (9, 7);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (9, 8);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (10, 9);
insert into timetable.lessons_teachers (lesson_id, teacher_id) values (10, 10);

insert into timetable.groups_lessons (group_id, lesson_id) values (1, 1);
insert into timetable.groups_lessons (group_id, lesson_id) values (1, 7);
insert into timetable.groups_lessons (group_id, lesson_id) values (1, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (1, 8);
insert into timetable.groups_lessons (group_id, lesson_id) values (1, 3);
insert into timetable.groups_lessons (group_id, lesson_id) values (2, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (2, 3);
insert into timetable.groups_lessons (group_id, lesson_id) values (2, 6);
insert into timetable.groups_lessons (group_id, lesson_id) values (2, 9);
insert into timetable.groups_lessons (group_id, lesson_id) values (2, 4);
insert into timetable.groups_lessons (group_id, lesson_id) values (3, 3);
insert into timetable.groups_lessons (group_id, lesson_id) values (3, 8);
insert into timetable.groups_lessons (group_id, lesson_id) values (3, 10);
insert into timetable.groups_lessons (group_id, lesson_id) values (3, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (3, 2);
insert into timetable.groups_lessons (group_id, lesson_id) values (4, 9);
insert into timetable.groups_lessons (group_id, lesson_id) values (4, 2);
insert into timetable.groups_lessons (group_id, lesson_id) values (4, 7);
insert into timetable.groups_lessons (group_id, lesson_id) values (4, 10);
insert into timetable.groups_lessons (group_id, lesson_id) values (4, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (5, 10);
insert into timetable.groups_lessons (group_id, lesson_id) values (5, 4);
insert into timetable.groups_lessons (group_id, lesson_id) values (5, 8);
insert into timetable.groups_lessons (group_id, lesson_id) values (5, 9);
insert into timetable.groups_lessons (group_id, lesson_id) values (5, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (6, 9);
insert into timetable.groups_lessons (group_id, lesson_id) values (6, 7);
insert into timetable.groups_lessons (group_id, lesson_id) values (6, 10);
insert into timetable.groups_lessons (group_id, lesson_id) values (6, 1);
insert into timetable.groups_lessons (group_id, lesson_id) values (6, 4);
insert into timetable.groups_lessons (group_id, lesson_id) values (7, 4);
insert into timetable.groups_lessons (group_id, lesson_id) values (7, 10);
insert into timetable.groups_lessons (group_id, lesson_id) values (7, 2);
insert into timetable.groups_lessons (group_id, lesson_id) values (7, 9);
insert into timetable.groups_lessons (group_id, lesson_id) values (7, 6);
insert into timetable.groups_lessons (group_id, lesson_id) values (8, 6);
insert into timetable.groups_lessons (group_id, lesson_id) values (8, 4);
insert into timetable.groups_lessons (group_id, lesson_id) values (8, 7);
insert into timetable.groups_lessons (group_id, lesson_id) values (8, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (8, 1);
insert into timetable.groups_lessons (group_id, lesson_id) values (9, 6);
insert into timetable.groups_lessons (group_id, lesson_id) values (9, 7);
insert into timetable.groups_lessons (group_id, lesson_id) values (9, 8);
insert into timetable.groups_lessons (group_id, lesson_id) values (9, 3);
insert into timetable.groups_lessons (group_id, lesson_id) values (9, 1);
insert into timetable.groups_lessons (group_id, lesson_id) values (10, 5);
insert into timetable.groups_lessons (group_id, lesson_id) values (10, 1);
insert into timetable.groups_lessons (group_id, lesson_id) values (10, 2);
insert into timetable.groups_lessons (group_id, lesson_id) values (10, 3);
insert into timetable.groups_lessons (group_id, lesson_id) values (10, 10);

